# Generated by Django 2.2.4 on 2020-08-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(default='normal', max_length=100),
            preserve_default=False,
        ),
    ]
