# Generated by Django 2.2.4 on 2020-08-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0002_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='put description here'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
