# Generated by Django 2.2.4 on 2020-08-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_and_ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='no description', max_length=255),
            preserve_default=False,
        ),
    ]
